"""
monitoring/intelligence_loop.py
================================
STEP 4 (Autonomous Phase) — Autonomous Intelligence Loop

Continuously monitors:
  - market conditions (from Redis hot cache)
  - weather signals (from weather service)
  - alerts generated by the monitor
  - volatility regime
  - risk score changes

Generates actionable intelligence summaries WITHOUT user prompting.
Writes insights to Redis key: coffee:live:intelligence_insights (list)
"""
from __future__ import annotations

import asyncio
from datetime import datetime, timezone

from core.logger import logger
from streaming.redis_cache import RedisMarketCache

INTELLIGENCE_INTERVAL: int = 120   # 2 minutes between auto-analysis cycles
MAX_STORED_INSIGHTS: int   = 20


class IntelligenceLoop:
    """
    Autonomous intelligence loop — generates market insights without
    requiring a user question.

    Designed to run as a background asyncio.Task.
    """

    def __init__(
        self,
        cache: RedisMarketCache | None = None,
        market_service=None,
        weather_service=None,
    ) -> None:
        self._cache           = cache or RedisMarketCache()
        self._market_service  = market_service
        self._weather_service = weather_service
        self._running         = False
        self._cycle_count     = 0

    async def start(self) -> None:
        self._running = True
        logger.info("IntelligenceLoop started (interval={}s)", INTELLIGENCE_INTERVAL)
        while self._running:
            try:
                await self._intelligence_cycle()
            except asyncio.CancelledError:
                break
            except Exception as exc:
                logger.warning("IntelligenceLoop cycle error: {}", exc)
            await asyncio.sleep(INTELLIGENCE_INTERVAL)

    async def stop(self) -> None:
        self._running = False

    # ─── Intelligence cycle ───────────────────────────────────────────────────

    async def _intelligence_cycle(self) -> None:
        self._cycle_count += 1
        snapshot = await self._cache.get_live_snapshot()
        risk     = await self._cache.get_json("coffee:live:risk")
        alerts   = await self._cache.get_alerts(10)

        arabica   = snapshot.get("arabica") or {}
        robusta   = snapshot.get("robusta") or {}
        a_price   = float(arabica.get("arabica_price") or 0)
        r_price   = float(robusta.get("robusta_price") or 0)
        a_change  = float(arabica.get("change_percent") or 0)
        r_change  = float(robusta.get("change_percent") or 0)

        risk_level = (risk or {}).get("risk_level", "unknown")
        risk_score = float((risk or {}).get("risk_score") or 0)

        # Build insight payload
        insight = self._build_insight(
            a_price=a_price, r_price=r_price,
            a_change=a_change, r_change=r_change,
            risk_level=risk_level, risk_score=risk_score,
            alerts=alerts,
        )

        await self._cache.push_list_json(
            "coffee:live:intelligence_insights",
            insight,
            max_length=MAX_STORED_INSIGHTS,
            ttl=3600,
        )

        logger.info(
            "IntelligenceLoop cycle #{} | risk={} insight={}",
            self._cycle_count, risk_level, insight["headline"][:60],
        )

    # ─── Insight builder ─────────────────────────────────────────────────────

    def _build_insight(
        self,
        a_price: float,
        r_price: float,
        a_change: float,
        r_change: float,
        risk_level: str,
        risk_score: float,
        alerts: list,
    ) -> dict:
        now_str = datetime.now(timezone.utc).isoformat()

        # Classify market condition
        avg_change  = (a_change + r_change) / 2 if a_price and r_price else a_change or r_change
        divergence  = abs(a_change - r_change)
        spike_alerts = [a for a in alerts if a.get("type") == "price_spike"]

        if spike_alerts:
            condition = "spike_detected"
            headline = (
                f"Price spike detected in {spike_alerts[0].get('market', 'coffee')} market — "
                f"immediate attention required."
            )
        elif risk_level == "high":
            condition = "high_risk"
            headline = (
                f"Coffee market risk elevated (score {risk_score:.0f}/100). "
                "Arabica and Robusta showing increased volatility."
            )
        elif divergence >= 2.0:
            condition = "divergence"
            winner = "Arabica" if a_change > r_change else "Robusta"
            loser  = "Robusta" if winner == "Arabica" else "Arabica"
            headline = (
                f"Market divergence: {winner} outperforming {loser} by {divergence:.1f}%. "
                "Blending economics may shift."
            )
        elif avg_change >= 1.5:
            condition = "bullish"
            headline = (
                f"Coffee futures showing broad bullish momentum ({avg_change:+.1f}% average). "
                "Supply concerns may be driving prices."
            )
        elif avg_change <= -1.5:
            condition = "bearish"
            headline = (
                f"Coffee futures under selling pressure ({avg_change:+.1f}% average). "
                "Watch export levels and demand signals."
            )
        else:
            condition = "stable"
            headline = (
                "Coffee market conditions remain stable. "
                "No significant price movements detected in the current session."
            )

        body = self._build_insight_body(
            condition=condition, a_price=a_price, r_price=r_price,
            a_change=a_change, r_change=r_change,
            risk_level=risk_level, risk_score=risk_score,
        )

        return {
            "cycle": self._cycle_count,
            "condition": condition,
            "headline": headline,
            "body": body,
            "arabica_price": a_price,
            "robusta_price": r_price,
            "arabica_change_pct": a_change,
            "robusta_change_pct": r_change,
            "risk_level": risk_level,
            "risk_score": risk_score,
            "generated_at": now_str,
            "source": "intelligence_loop",
        }

    def _build_insight_body(
        self,
        condition: str,
        a_price: float,
        r_price: float,
        a_change: float,
        r_change: float,
        risk_level: str,
        risk_score: float,
    ) -> str:
        lines = []
        if a_price > 0:
            lines.append(
                f"Arabica: {a_price:.2f} US cents/lb ({a_change:+.2f}%)."
            )
        if r_price > 0:
            lines.append(
                f"Robusta: {r_price:.0f} USD/tonne ({r_change:+.2f}%)."
            )

        if risk_level == "high":
            lines.append(
                f"Risk score: {risk_score:.0f}/100 — market conditions suggest caution. "
                "Farmers may benefit from delaying bulk sales if volatility persists."
            )
        elif risk_level == "medium":
            lines.append(
                f"Risk score: {risk_score:.0f}/100 — moderate uncertainty. "
                "Standard hedging strategies remain appropriate."
            )
        else:
            lines.append(
                f"Risk score: {risk_score:.0f}/100 — low volatility environment."
            )

        if condition == "divergence":
            lines.append(
                "The spread between Arabica and Robusta is widening, "
                "which may affect blending ratios and roaster margin economics."
            )

        return " ".join(lines)
